version: '3'
services:
    web:
        image:
            podcast
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - ENV=web
        ports:
            - 127.0.0.1:${APP_PORT}:8000
        volumes:
            - ${PWD}/static:/podcast/static
        networks:
            - internal-subnet

    rq:
        image:
            podcast
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - ENV=rq
        networks:
            - internal-subnet

networks:
    internal-subnet:
        external: true
