version: '3'
services:
  web:
    image: podcast
    build:
      context: .
    env_file:
      - .env
    environment:
      - APP_SERVICE=web
    ports:
      - 127.0.0.1:${APP_PORT}:8000
    volumes:
      - ${PWD}/static:/podcast/static
    networks:
      - internal-subnet

  rq:
    image: podcast
    build:
      context: .
    env_file:
      - .env
    environment:
      - APP_SERVICE=rq
    networks:
      - internal-subnet

  test:
    image: podcast
    build:
      context: .
      args:
        DEV_DEPS: "true"
    env_file:
      - .env
    environment:
      - APP_SERVICE=test

networks:
  internal-subnet:
    external: true
